server:
  port: 8081
security:
  oauth2:
    client:
      clientId: clientID from Okta
      clientSecret: Client_secret from Okta
      accessTokenUri: okta_uri/v1/token
    resource:
      tokenInfoUri: okta_uri/v1/introspect